name: New Graph Request
description: New graph to brpubVJCE repository
title: "New Graph Request:  <Insert Issue Title Here>"
labels: ["new graph", "programming"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new graph request!  We love keeping brpubVJCE fresh!
  - type: textarea
    id: shell
    attributes:
      label: Figure Shell
      description: Give a figure shell for the requested new graph (could be a draft version)
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: x-axis
    attributes:
      label: X-axis
      description: Can you describe the X-axis?
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: y-axis
    attributes:
      label: Y-axis
      description: Can you describe the Y-axis?
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: graph_area_objects
    attributes:
      label: Graph Area Objects
      description: Can you describe the graph area objects (e.g., dots, lines, shaded areas)?
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: legend
    attributes:
      label: Legend
      description: Can you describe the legend?
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: input
    attributes:
      label: Relevant Input
      description: Can you provide what the input should look like?
      placeholder: "What should the input look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue"
    validations:
      required: false
  - type: textarea
    id: use
    attributes:
      label: Use of graph
      description: Can you describe the use of the graph?
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: code
    attributes:
      label: Reproducible Example/Pseudo Code
      description: Can you provide a working example or a sketch of how the code should work?
      placeholder: "We love example code and it will speed up the process! REMINDER: no patient level data or company sensitive information should be shared via this open public issue"
    validations:
      required: false
